### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xNiker** [xNiker/innovation#1]
# **Elektronika:**

**1. Płyta główna:**

- [ ] obszar zasilania (przetwornica 3,3V i 5V)
- [ ] obszar mikrokontorlera ATMEGA32U-PU
- [ ] obszar konwertera USB-UART/SPI FT232R (SMD z przejściówką DIP) - porgramowanie mikrokontrolera i obsługa portu szeregowego
- [ ] obszar sieciowy Ethernet ENC28j60
- [ ] obszar zegara RTC PCF8563P z własnym zasilaniem podtrzymującym (bateria 3,3V)
- [ ] obszar pamięci EEPROM 24C256 256Kb
- [ ] obsługa wyświetlacza LCD przez ekspander PCF8574

**2. Sterownik wentylatorów:**
- [ ] zbudowany na tranzystorach MOSFET z separacją galwaniczną przez transoptory

**3. Sterownik grzałki**
- [ ] zbudowany na traiku z separacją przez optotraik MOC

**4. Zasilanie:**
- [ ] ze sklepu 12V 10A dla elektroniki, wentylatorów i silnika krokowego
- [ ] płytka z przetwornicami STEP-DOWN 3V3, 5V

**5. Płytka z portem USB**

# Program w C dla mikrokontrolera:

- [ ] napisanie biblioteki do obsługi wielozadaniowość i kolejki zadań

- [ ] napisanie biblioteki do obsługi interfejsu SPI
- [ ] napisanie biblioteki do obsługi interfejsu I2C
- [ ] napisanie biblioteki do obsługi interfejsu UART
- [ ] napisanie biblioteki do obsługi interfejsu OneWire
- [ ] napisanie biblioteki do obsługi przetwornika ADC
- [ ] napisanie biblioteki do obsługi zegara RTC PCF8563P - interfejs I2C
- [ ] napisanie biblioteki do obsługi ekspandera PCF8574 - interfejs I2C
- [ ] napisanie biblioteki do obsługi pamięci EEPROM 24c256 - interfejs I2C
- [ ] napisanie biblioteki do obsługi silnika krokowego - sterownik
- [ ] napisanie biblioteki do obsługi czujników temperatury LM35DZ - przetwornik ADC
- [ ] napisanie biblioteki do obsługi wyświetlacza LCD
- [ ] rozszerzenie biblioteki do obsługi wyświetlacza LCD o sterowanie przez ekspander PCF8574
- [ ] napisanie biblioteki do obsługi enkodera obrotowego
- [ ] napisanie biblioteki do obsługi wentylatorów i grzałki
- [ ] napisanie biblioteki do obsługi ENC28j60 - interfejs SPI
- [ ] napisanie biblioteki do obsługi terminala portu szeregowego - do debugowania
- [ ] napisanie biblioteki do obsługi enkodera - przerwania INT0, INT1
- [ ] stworzenie struktury menu dla wyświetlacza LCD
- [ ] napisanie biblioteki do obsługi poruszania się po menu
- [ ] napisanie biblioteki do obsługi sieci:
- implementacja stosu IP
- implementacja biblioteki do obsługi ENC28j60
- obsługa requestów i callback ARP
- obsługa protokołu TCP	
- obsługa protokołu UDP
- obsługa protokołu HTTP	
- obsługa serwera UDP
- obsługa echo ICMP
- [ ] napisanie biblioteki do sczytywania programu suszenia z EEPROM
- [ ] napisanie parsera JSON (struktura przesyłanych informacji)
- [ ] obsługa komend UDP/HTTP i lokalnych, wybranych na wyświetlaczu
- [ ] obsługa programu suszenia
	
# Podział task-ów programu (zadań):

**TASK1:**
- obsługa sieci, nasłuchiwanie na porcie UDP/HTTP

**TASK2:**
- obsługa terminala portu szeregowego, debugowanie

**TASK3:**
- obsługa wyświetlacza LCD i menu

**TASK4:**
- obsługa komend z UDP/HTTP i wyświetlacza

**TASK5:**
- obsługa enkodera i przycisków

**TASK6:**
- zbieranie informacji z czujników

**TASK7:**
- kontrola programu suszenia
